name: Django CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r djangoProject/requirements.txt
    - name: Run Tests
      run: |
        cd djangoProject && python manage.py test
    - name: Build Docker image
      run: |
        docker build -t m4llhew/test2:latest .
        docker push m4llhew/test2:latest
    - name: Deploy to Render
      uses: renderapp/action@v1
      with:
        args: 'deploy --env <your-render-environment-name>'

